name: chocolatine
on: [push, pull_request]
jobs:
    check_compile:
        runs-on: unbuntu-lastest
        steps:
            - name: checking out the repository
                run: echo "First test"
